CREATE TABLE booking.HOTEL(
    ID INT PRIMARY KEY,
    HOTEL_NAME VARCHAR NOT NULL,
    REGULATION VARCHAR,
    CITY VARCHAR,
    REGION VARCHAR,
    ROAD_AND_NUMBER VARCHAR,
    CERTIFICATE_NUMBER VARCHAR,
    IMAGE_PATH VARCHAR,
	MEMBER_ID INT NOT NULL,
    FOREIGN KEY(MEMBER_ID) REFERENCES booking.MEMBER(MEMBER_ID)
);

-- ROOM
CREATE TABLE booking.ROOM(
    ID INT PRIMARY KEY,
    ROOM_NAME VARCHAR NOT NULL,
    QUANTITY INT,
    CAPACITY INT,
    PRICE INT,
    IMAGE_PATH VARCHAR,
	HOTEL_ID INT NOT NULL,
    FOREIGN KEY(HOTEL_ID) REFERENCES booking.HOTEL(ID)
);
-- facilities
CREATE TABLE booking.FACILITIES(
    ID INT PRIMARY KEY,
    FACILITY_NAME VARCHAR
);
CREATE TABLE booking.ROOM_FACILITY(   -- relation between room and facility
    ID INT PRIMARY KEY,
    FACILITY_ID INT NOT NULL,
    ROOM_ID INT NOT NULL,
    FOREIGN KEY(FACILITY_ID) REFERENCES booking.FACILITIES(ID),
    FOREIGN KEY(ROOM_ID) REFERENCES booking.ROOM(ID)
);
-- services
CREATE TABLE booking.SERVICES(
    ID INT PRIMARY KEY,
    SERVICES_NAME VARCHAR
);
CREATE TABLE booking.ROOM_SERVICE(   -- relation between room and facility
    ID INT PRIMARY KEY,
    SERVICES_ID INT NOT NULL,
    ROOM_ID INT NOT NULL,
    FOREIGN KEY(SERVICES_ID) REFERENCES booking.SERVICES(ID),
    FOREIGN KEY(ROOM_ID) REFERENCES booking.ROOM(ID)
);


-- Stars and Comments
CREATE TABLE booking.RATING(
    ID INT PRIMARY KEY,
    EVALUATION INT NOT NULL,
    COMMENTS VARCHAR,
	IMAGE_PATH VARCHAR,
    HOTEL_ID INT NOT NULL,
	MEMBER_ID INT NOT NULL,
    FOREIGN KEY(HOTEL_ID) REFERENCES booking.HOTEL(ID),
    FOREIGN KEY(MEMBER_ID) REFERENCES booking.MEMBER(MEMBER_ID)
);
